Finished jgen and jval

diff --git a/bin/jval b/bin/jval
--- a/bin/jval
+++ b/bin/jval
@@ -1,14 +1,24 @@
 #!/bin/bash
 #
-# Validates an instance document against a JSON schema.
+# Validates instance documents against a JSON schema.
 #
+# Joan Ordinas <jordinas@gmail.com>
 
-# Bash options
-set -o errexit -o noglob -o nounset -o pipefail
-shopt -s expand_aliases
+########################################################################
+# Environment
+########################################################################
 
-# jval version
+# Script version
 declare -r VERSION='0.1'
+
+# Data directory: edit if necessary
+declare -r DATADIR='/usr/local/share'
+
+# JBOL modules path
+declare -r MODULES="${DATADIR}/jbol"
+
+# Meta schema
+declare -r METASCHEMA="${DATADIR}/jbol/schemata/schema.schema.json"
 
 # This script name
 declare -r SELF="${0##*/}"
@@ -16,14 +26,17 @@ declare -r SELF="${0##*/}"
 # JQ script
 declare -r JQ="${0}.jq"
 
-# JBOL modules path
-declare -r JBOL='-L/usr/local/share/jbol'
+########################################################################
+# Functions and aliases
+########################################################################
 
-# Meta schema
-declare -r METASCHEMA='/usr/local/share/jbol/schemata/schema.schema.json'
+# Bash options
+set -o errexit -o noglob -o nounset -o pipefail
+shopt -s expand_aliases
 
 # Print text on screen
 alias print='echo 1>&2 -e'
+alias message='cat 1>&2'
 
 # Abort with message
 function fatal {
@@ -33,18 +46,33 @@ function fatal {
 
 # Show help
 function help {
-    cat 1>&2 <<EOF
-${SELF} - validates a JSON document
-Usage: ${SELF} [options] schema [file]
+    message <<EOF
+${SELF} -- Validates instance documents against a JSON schema
 
-${SELF} validates against an schema a JSON instance document read from a file
-or the standard input.
+Usage: ${SELF} [-h | --help | -v | --version]
+       ${SELF} [options...] schema [file...]
+
+${SELF} validates against an schema a JSON instance document read from the
+standard input.  One or more files may be specified, in which case jval will
+read input from those instead.
 
 Options:
     -h, --help              Show this help
-    -s, --schema            Validates JSON schema against the meta schema
+    -q, --quiet             Suppress all normal output (status is zero or one)
+    -s, --schema            Validates a JSON schema against the meta schema
+    -v, --version           Print version information
 EOF
     exit $(( $# == 0 ))
+}
+
+# Print usage message and exit
+function usage {
+    message <<EOF
+Unknown option: $1
+Usage: ${SELF} [-h | --help | -v | --version]
+       ${SELF} [options] schema [file]
+EOF
+    exit 1
 }
 
 # Print version and exit
@@ -53,38 +81,35 @@ function version {
     exit 0
 }
 
-# Print usage message and exit
-function usage {
-    print "Unknown option: $1\n"
-    print "Usage: ${SELF} [-h | --help | -V]"
-    print "Usage: ${SELF} [options] schema [file]"
-    exit 1
-}
-
 # Validates document
 function validate {
     local schema=$1
-    jq $JBOL                        \
+    jq  -L $MODULES                 \
         --from-file ${JQ}           \
         --raw-output                \
         --slurpfile SCHEMA $schema  \
         "$@"
 }
 
+########################################################################
 # Entry point
+########################################################################
+
 function main {
-    local -i metaschema=0
+    local -i metaschema=0 quiet=0
 
     local opt
-    while getopts :Vhs-: opt; do
+    while getopts :hqsv-: opt; do
         case $opt in
-            V) version ;;
             h) help ;;
+            q) quiet=1 ;;
             s) metaschema=1 ;;
+            v) version ;;
             -) case $OPTARG in
-                   version) version ;;
                    help) help ;;
+                   quiet) quiet=1 ;;
                    schema) metaschema=1 ;;
+                   version) version ;;
                    *) usage "--$OPTARG";;
                esac
                ;;
@@ -95,10 +120,13 @@ function main {
     shift $((OPTIND-1))
     (( $# > 0 )) || help
 
+    [[ -e $MODULES ]] ||
+        fatal "$MODULES modules directory does not exists"
+    [[ -e $METASCHEMA ]] ||
+        fatal "missing $METASCHEMA meta schema"
+
     local schema diagnostic
     if ((metaschema)); then
-        [[ -e $METASCHEMA ]] ||
-			fatal "missing $METASCHEMA meta schema"
         schema=$METASCHEMA
     else
         schema=$1; shift
@@ -108,7 +136,7 @@ function main {
     if [[ -z $diagnostic ]]; then
         return 0
     else
-        print $diagnostic
+        (( quiet )) || print $diagnostic
         return 1
     fi
 }
